name: Deploy

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build page
      run: |
        npm install
        npm run build
        cp CNAME dist
        cp sitemap.xml dist
        touch dist/.nojekyll

    - name: Publish github pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/brunoanc/brunoanc.github.io.git
        npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
